version: '3.9'

services:
  app:
    build: .
    container_name: dynamic_pricing_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - ENV=development
    command: python main.py
